services:
  database:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - valeecookies-db-data:/var/lib/postgresql/data
    networks:
      - valeecookies-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: unless-stopped
    depends_on:
      - database
    expose:
      - "8000"
    networks:
      - valeecookies-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    expose:
      - "80"
    networks:
      - valeecookies-network

networks:
  valeecookies-network:
    driver: bridge

volumes:
  valeecookies-db-data:
    external: true
    name: valeecokies_valeecookies-db-data
